version: "3.8"

services:
  app:
    build: .
    container_name: elearning_frankenphp
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - ./database:/app/database
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SERVER_NAME=${SERVER_NAME:-localhost}
    depends_on:
      - redis
    networks:
      - elearning-network
    tty: true

  redis:
    image: redis:7-alpine
    container_name: elearning_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - elearning-network
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  elearning-network:
    driver: bridge
