version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: elearning-app
        container_name: elearning-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - database
            - redis
        networks:
            - elearning-network

    webserver:
        image: nginx:alpine
        container_name: elearning-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - elearning-network

    database:
        image: mysql:8.0
        container_name: elearning-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-elearning}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_USER: ${DB_USERNAME:-elearning}
        volumes:
            - database_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - elearning-network

    redis:
        image: redis:7-alpine
        container_name: elearning-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - elearning-network

    node:
        image: node:18-alpine
        container_name: elearning-node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        depends_on:
            - app
        networks:
            - elearning-network

volumes:
    database_data:
        driver: local
    redis_data:
        driver: local

networks:
    elearning-network:
        driver: bridge
