version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: elearning_app_prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage/app:/var/www/storage/app
      - ./storage/logs:/var/www/storage/logs
    environment:
      - CONTAINER_ROLE=app
    depends_on:
      - database
      - redis
    networks:
      - elearning-network

  webserver:
    image: nginx:alpine
    container_name: elearning_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - elearning-network

  certbot:
    image: certbot/certbot
    container_name: elearning_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./:/var/www
    command: certonly --webroot --webroot-path=/var/www/public --email your-email@domain.com --agree-tos --no-eff-email --staging -d your-domain.com -d www.your-domain.com
    networks:
      - elearning-network

  database:
    image: mysql:8.0
    container_name: elearning_db_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data_prod:/var/lib/mysql
      - ./docker/mysql/backup:/backup
    ports:
      - "3306:3306"
    networks:
      - elearning-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: elearning_redis_prod
    restart: unless-stopped
    volumes:
      - redis_data_prod:/data
    networks:
      - elearning-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  backup:
    image: alpine:latest
    container_name: elearning_backup
    restart: "no"
    volumes:
      - database_data_prod:/var/lib/mysql:ro
      - ./storage/backups:/backups
      - ./docker/scripts:/scripts
    depends_on:
      - database
    networks:
      - elearning-network
    command: /scripts/backup.sh

volumes:
  database_data_prod:
    driver: local
  redis_data_prod:
    driver: local
  certbot-etc:
    driver: local
  certbot-var:
    driver: local

networks:
  elearning-network:
    driver: bridge
