services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_production_app
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - caddy_data:/data
        env_file:
            - .env

volumes:
    app_storage:
        driver: local
    app_database:
        driver: local
    caddy_data:
        driver: local
